# Generated by Django 3.0.3 on 2020-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conversion_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
